---
---
version: '3'
services:
  voting-app:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5050:80
    deploy:
      replicas: 2
  redis-app:
    image: redis
    ports:
      - 6379:6379
  worker-app:
    image: dockersamples/examplevotingapp_worker
  postgres-app:
    image: postgres
    environment:
      POSTGRES_PASSWORD: intelliq
      POSTGRES_USER: myuser
      POSTGRES: mydb
  result-app:
    image: dockersamples/examplevotingapp_result
    ports:
      - 6060:80
    deploy:
      replicas: 2
...

