---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    author: intelliq
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key:  a
