---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  namespace: test-ns
  labels:
    type: ci-cd
    author: intelliq
spec:
  replicas: 3
  selector:
    matchLabels:
      type: ci-cd
  template:
    metadata:
      name: jenkins-pods
      labels:
        type: ci-cd
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 9090
