apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-db
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mysql-db
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: intelliqit
          image: mysql
          name: mysql-db
      restartPolicy: Always
