---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  pod-reader
  namespace: example-namespace
rules:
  - apiGroups: [" "]
    resources: ["pod"]
    verbs: ["get","list","watch"]
...


